/////////////////////////////////////////////////////////////////////////////////////////////
// Copyright 2023 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/////////////////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.105Release
// Tag = production/release/21.105.00-0-gdc65d24
/////////////////////////////////////////////////////////////////////////////////////////////


#if !defined(FIT_RUNTIME_EXCEPTION_HPP)
#define FIT_RUNTIME_EXCEPTION_HPP

#include <stdexcept>
#include <string>

namespace fit
{

class RuntimeException : public std::runtime_error
{
public:
    RuntimeException(const std::string& msg = "")
        : runtime_error(msg)
    {
    }
};

} // namespace fit

#endif // !defined(FIT_RUNTIME_EXCEPTION_HPP)
